site_name: PygameUI
site_description: Documentation for PygameUI library
site_author: Trym Bringsrud Fekj√¶r
site_url: https://trymbf.github.io/PygameUI
repo_url: https://github.com/trymbf/PygameUI

theme:
  name: material
  logo: assets/imgs/logo.png
  favicon: assets/imgs/logo.png
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

#plugins:
#  - with-pdf:
#      cover_subtitle: Python library that makes making pygame-based-UIs easy!
#      cover_logo: assets/logo.png

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Components:
      - Index: components/index.md
      - Overview: components/overview.md
      - Element: components/element.md
      - Text: components/text.md
      - Button: components/button.md
      - Image: components/image.md
      - Input: components/input.md
      - Checkbox: components/checkbox.md
      - Progress Bar: components/progress-bar.md
      - Dropdown Menu: components/dropdown-menu.md
      - Table: components/table.md
  - Examples:
      - Index: examples/index.md
      - Button Example: examples/button.md
      - Input Form Example: examples/form.md
      - Animation Demo: examples/animation.md
      - Simple Game: examples/game.md
  - Troubleshooting: troubleshooting.md
  - API Reference: api-reference.md
